#application-prod.yml
spring:
  datasource:
    # Railway MySQL 연결 형식 수정
    url: ${DATABASE_URL}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  data:
    redis:
      # Railway Redis 연결 정보
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update  # 첫 배포시는 update, 이후 validate로 변경
    show-sql: false        # 운영은 false 권장?
    format-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  jwt:
    secret: ${JWT_SECRET}
    expiration: 2592000000
    refresh-expiration: 2592000000

  server:
    port: ${PORT:8080}  # Railway PORT 환경변수 사용
    servlet:
      context-path: /api

  management:
    endpoints:
      web:
        exposure:
          include: health

