#application.yml
spring:
  profiles:
    active: dev # 로컬 환경과 서버 환경의 application.yml 설정이 달라서 기본(dev), 서버(prod로 override 예정)
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

  # Redis 설정 추가
  data:
    redis:
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0


  jpa:
    hibernate:
      ddl-auto: update  # 운영: validate, 개발: update
    show-sql: true        # SQL 쿼리 로그 출력, 운영은 false 권장
    format-sql: true      # SQL 포맷팅
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.springframework.orm.jpa: DEBUG
      org.springframework.transaction: DEBUG


jwt:
  expiration: 2592000000 # 1달
  refresh-expiration: 2592000000 # 1달
server:
  port: 8080
  servlet:
    context-path: /api


# 도지정향토음식점 정보
do-store:
  api:
    base-url: https://apis.data.go.kr/6450000/DoRestaurantService
    endpoints:
      get-stores-list: getDoRestaurant          # 도지정향토음식점목록 조회
      get-stores-Detail: getDoRestaurantDetail  # 도지정향토음식점상세보기 조회
    service-key: ${DORESTAURANT_SERVICE_KEY}

#향토음식점서비스
jb-store:
  api:
    base-url: https://apis.data.go.kr/6450000/JeonbukRestaurantService
    endpoints:
      get-stores-list: getJeonbukRestaurant        # 전북향토음식점상세보기 조회
      get-stores-Detail: getJeonbukRestaurantDetail # 전북향토음식점상세보기 조회
    service-key: ${DORESTAURANT_SERVICE_KEY}

# 카카오
kakao:
  api:
    rest-key: ${KAKAO_MAPS_KEY}

#open-ai
openai:
  api:
    key: ${OPENAI_API_KEY}